"""Added tables

Revision ID: 213173bb93a7
Revises: 
Create Date: 2023-07-24 10:44:52.142124

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '213173bb93a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.Column('income', sa.Integer(), nullable=True),
                    sa.Column('another_loans', sa.Boolean(), nullable=True),
                    sa.Column('birth_date', sa.Date(), nullable=True),
                    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=True),
                    sa.Column('status_document', sa.Boolean(), nullable=False),
                    sa.Column('status_face', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('credit_card',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('limit', sa.Integer(), nullable=False),
                    sa.Column('balance', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('exp_date', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
